name: NPM Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Set package version
        working-directory: npm
        run: npm version "\${GITHUB_REF_NAME#v}" --no-git-tag-version

      - name: Publish
        run: npm publish ./npm --access public
